version: '3'

services:

  frontend:
    build: new/frontend
    image: noobrainer-frontend:latest
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./new/frontent:/app
      - ./models:/app/models
      - ./data:/app/data
      - ./utils:/app/utils

  backend:
    build: new/backend
    image: noobrainer-backend:latest
    ports:
      - 8000:8000
    volumes:
      - ./new/backend:/app
      - ./models:/app/models
      - ./data:/app/data
      - ./utils:/app/utils
